version: '3'

volumes:
  prometheus_data: {}


services:
  prometheus:
    image: prom/prometheus:v2.31.1
    volumes: 
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--enable-feature=exemplar-storage'
    ports: 
      - 9090:9090
  collector-agent:
    image: otel/opentelemetry-collector-contrib:0.75.0
    # image: otel/opentelemetry-collector-contrib@sha256:d900e061d98fca1d25936a7f99023a8dfcdbc720d51db37692082768fc172b85
    volumes: 
      - ./config/collector-agent.yml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4320:4320"   # OTLP gRPC receiver
      - "4321:4321"        # OTLP HTTP receiver
      - "8889:8889"
  
    