# Please, don't use any default port allocations.
# https://github.com/prometheus/prometheus/wiki/Default-port-allocations
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['<your ip>:8889']